import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { KeyRound, Monitor } from 'lucide-react';
import { useAdmin, useAdminText, useAdminMutation } from '../components/AdminContext.jsx';
import { Heading, Panel, Identity, Badge, Field, SelectField, Button, Confirmation, QueryState, DateValue, Empty, UnsavedGuard } from '../components/AdminUI.jsx';
import { platformAdminApi as api } from '../api/platformAdminApi.js';

export function ProfilePage() {
  const admin = useAdmin(), { t, locale, setLocale } = useAdminText(), [name, setName] = useState(admin.principal.name || ''), [language, setLanguage] = useState(admin.principal.language || locale), [saved, setSaved] = useState({ name: admin.principal.name || '', language: admin.principal.language || locale });
  const mutation = useAdminMutation(), dirty = name !== saved.name || language !== saved.language;
  const save = async e => { e.preventDefault(); try { await mutation.mutateAsync({ domain: 'account', action: 'profile', payload: { name, language } }); setSaved({ name, language }); setLocale(language); } catch { /* Hook reports translated error. */ } };
  return <><UnsavedGuard dirty={dirty} /><Heading title="profile" description="profileDescription" /><Panel title={t('account')}><form className="pa-editor-body" onSubmit={save}><div className="pa-detail-hero"><Identity name={admin.principal.name} email={admin.principal.email} /><Badge value={admin.principal.role} /></div><div className="pa-form-grid"><Field label={t('name')} value={name} maxLength={150} required onChange={e => setName(e.target.value)} /><Field label={t('email')} type="email" readOnly value={admin.principal.email || ''} /><SelectField label={t('language')} value={language} onChange={setLanguage} options={[{ value: 'en', label: t('english') }, { value: 'ar', label: t('arabic') }]} /></div><p className="pa-muted">{t('roleLocked')}</p><div className="pa-actions"><Button variant="outline" disabled={!dirty} onClick={() => { setName(saved.name); setLanguage(saved.language); }}>{t('cancel')}</Button><Button type="submit" disabled={!dirty || !name.trim()} loading={mutation.isPending} loadingLabel={t('saving')}>{t('save')}</Button></div></form></Panel></>;
}
export function SecurityPage() {
  const admin = useAdmin(), { t } = useAdminText(), [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' }), [dialog, setDialog] = useState(null);
  const mutation = useAdminMutation();
  const query = useQuery({ queryKey: ['platform-admin', admin.principal.id, 'sessions'], queryFn: () => api.account('sessions'), retry: false });
  const valid = passwords.currentPassword && passwords.newPassword.length >= 12 && passwords.newPassword === passwords.confirmPassword && passwords.newPassword !== passwords.currentPassword;
  const execute = async () => { try { await mutation.mutateAsync({ domain: 'account', action: dialog.action, payload: dialog.action === 'password' ? { currentPassword: passwords.currentPassword, newPassword: passwords.newPassword } : { id: dialog.id } }); setDialog(null); setPasswords({ currentPassword: '', newPassword: '', confirmPassword: '' }); } catch { /* Passwords never enter logs or query keys. */ } };
  return <><Heading title="security" description="securityDescription" /><div className="pa-two-columns"><Panel title={t('password')}><form className="pa-editor-body" onSubmit={e => { e.preventDefault(); if (valid) setDialog({ action: 'password' }); }}><KeyRound className="pa-section-icon" size={25} /><p className="pa-muted">{t('passwordNote')}</p>{Object.keys(passwords).map(key => <Field key={key} label={t(key)} type="password" required autoComplete={key === 'currentPassword' ? 'current-password' : 'new-password'} value={passwords[key]} onChange={e => setPasswords(v => ({ ...v, [key]: e.target.value }))} />)}{passwords.confirmPassword && passwords.confirmPassword !== passwords.newPassword && <p className="pa-error" role="alert">{t('passwordMismatch')}</p>}<Button type="submit" disabled={!valid}>{t('password')}</Button></form></Panel><Panel title={t('sessions')}><p className="pa-paragraph pa-muted">{t('sessionsNote')}</p><QueryState query={query}>{query.data?.items?.length ? <div className="pa-sessions">{query.data.items.map(session => <article key={session.id}><Monitor size={23} /><div><strong>{session.device === 'previewDevice' ? t('previewDevice') : session.device}</strong><small><DateValue value={session.lastActive} time /></small>{session.current && <Badge value="currentSession" />}</div>{!session.current && <Button variant="ghost" size="sm" onClick={() => setDialog({ action: 'revoke', id: session.id })}>{t('revoke')}</Button>}</article>)}{query.data.items.some(s => !s.current) && <Button variant="outline" onClick={() => setDialog({ action: 'revokeOthers' })}>{t('revokeOthers')}</Button>}</div> : <Empty message="noSessions" />}</QueryState></Panel></div><Confirmation open={Boolean(dialog)} title={t(dialog?.action === 'password' ? 'password' : dialog?.action === 'revoke' ? 'revoke' : 'revokeOthers')} busy={mutation.isPending} onClose={() => setDialog(null)} onConfirm={execute}><p>{t('sensitive')}</p></Confirmation></>;
}
