import { collectChanges } from '../api/changes.js';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Layers3, Check } from 'lucide-react';
import { useAdmin, useAdminQuery, useAdminMutation, useAdminText } from '../components/AdminContext.jsx';
import { Heading, Panel, QueryState, Badge, DateValue, Field, SelectField, Tabs, Button, Confirmation, UnsavedGuard, Forbidden } from '../components/AdminUI.jsx';
import { FEATURE_KEYS, LIMIT_KEYS, BILLING_PERIODS } from '../../../shared/catalog/planCatalog.js';
import { validatePlan } from '../api/validation.js';

export function PlansPage() {
  const query = useAdminQuery('plans'), admin = useAdmin(), { t, locale } = useAdminText();
  return <><Heading title="plans" description="plansDescription" /><div className="pa-notice"><Layers3 size={18} /><span>{t('planSafety')}</span></div><QueryState query={query}><div className="pa-plan-grid">{query.data?.items.map(plan => <article className={`pa-panel pa-plan ${plan.featured ? 'pa-plan-featured' : ''}`} key={plan.id}><div className="pa-plan-top"><span className="pa-kpi-icon"><Layers3 size={23} /></span><Badge value={plan.status} /></div><h2>{plan.name[locale]}</h2><p>{plan.description[locale]}</p><div className="pa-plan-price">{plan.monthlyPrice === null ? t('negotiated') : new Intl.NumberFormat(locale, { style: 'currency', currency: plan.currency, maximumFractionDigits: 0 }).format(plan.monthlyPrice)}{plan.monthlyPrice !== null && <small> / {t('monthly')}</small>}</div><div className="pa-plan-meta"><span>{plan.trialDays ? `${plan.trialDays} آ· ${t('trialDays')}` : t('trialOff')}</span><span>{t('featuresCount', { count: Object.values(plan.entitlements).filter(v => v !== null).length })}</span></div><ul>{LIMIT_KEYS.map(key => <li key={key}><Check size={15} /><span>{t(key)}</span><b>{plan.limits?.[key] === null ? t('unlimited') : plan.limits?.[key] ?? t('negotiated')}</b></li>)}</ul><div className="pa-plan-cycles">{plan.billingOptions.map(key => <span key={key}>{t(key)}</span>)}</div><div className="pa-actions"><Link className="pa-link-button" to={`/admin/plans/${plan.id}`}>{t('view')}</Link>{admin.can('plans.manage') && <Link className="pa-link-button primary" to={`/admin/plans/${plan.id}/edit`}>{t('edit')}</Link>}</div>{plan.updatedAt && <small>{t('updatedAt')} آ· <DateValue value={plan.updatedAt} /></small>}</article>)}</div></QueryState></>;
}
export { collectChanges } from '../api/changes.js';
export function ChangesTable({ changes }) {
  const { t } = useAdminText();
  const display = (value, key) => value === null ? t(key.startsWith('limits.') ? 'unlimited' : 'unconfigured') : typeof value === 'boolean' ? t(value ? 'enabled' : 'disabled') : Array.isArray(value) ? value.map(v => t(v)).join(', ') : value == null ? '—' : ['status', 'language'].includes(key) ? t(value === 'en' ? 'english' : value === 'ar' ? 'arabic' : value) : String(value);
  return <div className="pa-table-scroll"><table><thead><tr><th>{t('field')}</th><th>{t('before')}</th><th>{t('after')}</th></tr></thead><tbody>{changes.map(change => <tr key={change.key}><th>{change.key.split('.').map(k => ['en', 'ar'].includes(k) ? t(k === 'en' ? 'english' : 'arabic') : t(k)).join(' آ· ')}</th><td>{display(change.before, change.key)}</td><td><strong>{display(change.after, change.key)}</strong></td></tr>)}</tbody></table></div>;
}
function PlanEditor({ plan, editing }) {
  const admin = useAdmin(), { t, locale } = useAdminText(), [baseline, setBaseline] = useState(plan), [draft, setDraft] = useState(() => structuredClone(plan)), [tab, setTab] = useState('general'), [review, setReview] = useState(false), [error, setError] = useState('');
  const mutation = useAdminMutation('plans.manage');
  const dirty = JSON.stringify(draft) !== JSON.stringify(baseline), changes = collectChanges(baseline, draft);
  const set = (key, value) => { setDraft(current => ({ ...current, [key]: value })); setError(''); };
  const nested = (group, key, value) => setDraft(current => ({ ...current, [group]: { ...current[group], [key]: value } }));
  const number = value => value === '' ? NaN : Number(value);
  const reviewChanges = event => { event.preventDefault(); try { validatePlan(draft); setReview(true); setError(''); } catch { setError(t('invalid')); } };
  const save = async () => { try { const saved = await mutation.mutateAsync({ domain: 'plans', id: plan.id, action: 'update', payload: draft }); setBaseline(saved); setDraft(structuredClone(saved)); setReview(false); } catch { /* Keep editor and review open. */ } };
  return <><UnsavedGuard dirty={editing && dirty} /><Link className="pa-back" to="/admin/plans">← {t('plans')}</Link><Heading title={editing ? 'edit' : 'configuration'} eyebrow="catalog" actions={!editing && admin.can('plans.manage') ? <Link className="pa-link-button primary" to={`/admin/plans/${plan.id}/edit`}>{t('edit')}</Link> : undefined} /><div className="pa-detail-hero"><h2>{plan.name[locale]}</h2><Badge value={draft.status} />{!editing && <span className="pa-muted">{t('readOnly')}</span>}{dirty && <Badge value="unsaved" />}</div><Tabs items={['general', 'pricing', 'trialSection', 'limits', 'entitlements']} value={tab} onChange={setTab} /><form onSubmit={reviewChanges}><fieldset disabled={!editing || mutation.isPending} className="pa-editor-fieldset"><Panel title={t(tab)}><div role="tabpanel" aria-label={t(tab)} className="pa-editor-body">
    {tab === 'general' && <div className="pa-form-grid">{['en', 'ar'].map(lang => <Field key={lang} label={t(lang === 'en' ? 'nameEn' : 'nameAr')} value={draft.name[lang]} maxLength={100} required dir={lang === 'ar' ? 'rtl' : 'ltr'} onChange={e => nested('name', lang, e.target.value)} />)}{['en', 'ar'].map(lang => <Field key={lang} label={t(lang === 'en' ? 'descriptionEn' : 'descriptionAr')}><textarea value={draft.description[lang]} maxLength={600} required dir={lang === 'ar' ? 'rtl' : 'ltr'} rows={3} onChange={e => nested('description', lang, e.target.value)} /></Field>)}<SelectField label={t('status')} value={draft.status} onChange={v => set('status', v)} options={['active', 'inactive'].map(v => ({ value: v, label: t(v) }))} /></div>}
    {tab === 'pricing' && <><div className="pa-form-grid"><Field label={t('monthlyPrice')} type="number" min={0} step="0.01" value={Number.isNaN(draft.monthlyPrice) ? '' : draft.monthlyPrice ?? ''} disabled={draft.id === 'custom'} onChange={e => set('monthlyPrice', number(e.target.value))} /><Field label={t('currency')} value={draft.currency} readOnly /></div><p className="pa-muted">{t(draft.id === 'custom' ? 'customNote' : 'currencyNote')}</p><h3>{t('billingOptions')}</h3><div className="pa-checkbox-row">{BILLING_PERIODS.map(period => <label key={period.value}><input type="checkbox" checked={draft.billingOptions.includes(period.value)} disabled={period.value === 'monthly'} onChange={e => set('billingOptions', e.target.checked ? [...draft.billingOptions, period.value] : draft.billingOptions.filter(v => v !== period.value))} />{t(period.value)}</label>)}</div><h3>{t('discounts')}</h3><div className="pa-form-grid">{BILLING_PERIODS.filter(p => p.months > 1).map(period => <Field key={period.value} label={t(period.value)} type="number" min={0} max={99.99} step="0.01" value={Number.isNaN(draft.discounts[period.value]) ? '' : draft.discounts[period.value]} onChange={e => nested('discounts', period.value, number(e.target.value))} />)}</div></>}
    {tab === 'trialSection' && <><label className="pa-check"><input type="checkbox" checked={draft.trialDays > 0} onChange={e => set('trialDays', e.target.checked ? 14 : 0)} />{t('trialEnabled')}</label><Field label={t('trialDays')} type="number" min={0} max={365} step={1} value={Number.isNaN(draft.trialDays) ? '' : draft.trialDays} onChange={e => set('trialDays', number(e.target.value))} /><p className="pa-muted">{t('trialNote')}</p></>}
    {tab === 'limits' && (draft.id === 'custom' && !draft.limits ? <p>{t('customNote')}</p> : <div className="pa-form-grid">{LIMIT_KEYS.map(key => <div key={key}><Field label={t(key)} type="number" min={0} step={key === 'storageGb' ? '0.1' : '1'} disabled={draft.limits?.[key] === null} value={draft.limits?.[key] == null || Number.isNaN(draft.limits[key]) ? '' : draft.limits[key]} onChange={e => nested('limits', key, number(e.target.value))} /><label className="pa-check"><input type="checkbox" checked={draft.limits?.[key] === null} onChange={e => nested('limits', key, e.target.checked ? null : 0)} />{t('unlimited')}</label></div>)}</div>)}
    {tab === 'entitlements' && <><p className="pa-muted">{t('featureNote')}</p><div className="pa-form-grid">{FEATURE_KEYS.map(key => <SelectField key={key} label={t(key)} value={String(draft.entitlements[key])} onChange={v => nested('entitlements', key, v === 'null' ? null : v === 'true')} options={[{ value: 'null', label: t('unconfigured') }, { value: 'true', label: t('enabled') }, { value: 'false', label: t('disabled') }]} />)}</div></>}
  </div></Panel></fieldset>{error && <p role="alert" className="pa-error">{error}</p>}{editing && <div className="pa-editor-footer"><p>{t('planSafety')}</p><Button variant="outline" disabled={!dirty} onClick={() => { setDraft(structuredClone(baseline)); setError(''); }}>{t('cancel')}</Button><Button type="submit" disabled={!dirty || mutation.isPending}>{t('review')}</Button></div>}</form><Confirmation open={review} title={t('review')} busy={mutation.isPending} onClose={() => setReview(false)} onConfirm={save}><p>{t('sensitive')}</p><h3>{draft.name[locale]}</h3><ChangesTable changes={changes} /></Confirmation></>;
}
export function PlanDetailPage({ editing = false }) { const { id } = useParams(), query = useAdminQuery('plans', {}, id), admin = useAdmin(); if (editing && !admin.can('plans.manage')) return <Forbidden />; return <QueryState query={query}>{query.data && <PlanEditor key={`${id}-${editing}`} plan={query.data} editing={editing} />}</QueryState>; }
export function FeaturesPage() {
  const query = useAdminQuery('plans'), { t, locale } = useAdminText(), admin = useAdmin();
  const plans = query.data?.items || [];
  return <><Heading title="features" description="featuresDescription" /><p className="pa-notice">{t('featureNote')}</p><QueryState query={query}>{[['entitlements', FEATURE_KEYS], ['limits', LIMIT_KEYS]].map(([group, keys]) => <Panel key={group} title={t(group)}><div className="pa-table-scroll" role="region" tabIndex={0} aria-label={t(group)}><table><thead><tr><th>{t(group)}</th>{plans.map(plan => <th key={plan.id}>{plan.name[locale]}</th>)}</tr></thead><tbody>{keys.map(key => <tr key={key}><th scope="row">{t(key)}</th>{plans.map(plan => { const value = plan[group]?.[key]; return <td key={plan.id}>{group === 'entitlements' ? value == null ? <span className="pa-muted">{t('unconfigured')}</span> : <Badge value={value ? 'enabled' : 'disabled'} /> : value === null ? t('unlimited') : value ?? t('negotiated')}</td>; })}</tr>)}</tbody><tfoot><tr><th>{t('configuration')}</th>{plans.map(plan => <td key={plan.id}><Link to={`/admin/plans/${plan.id}${admin.can('features.manage') ? '/edit' : ''}`}>{t(admin.can('features.manage') ? 'featureAccess' : 'view')}</Link></td>)}</tr></tfoot></table></div></Panel>)}</QueryState></>;
}



