export const ERROR_CODES = {
  // Authentication — 401
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_AUTH_HEADER: "INVALID_AUTH_HEADER",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Authorization — 403
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  TENANT_ACCESS_DENIED: "TENANT_ACCESS_DENIED",

  // Validation — 400 / 422
  INVALID_REQUEST: "INVALID_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_PARAMETER: "INVALID_PARAMETER",

  // Resources — 404
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  PROMO_CODE_NOT_FOUND: "PROMO_CODE_NOT_FOUND",

  // Conflicts — 409
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  TENANT_ALREADY_EXISTS: "TENANT_ALREADY_EXISTS",
  SUBSCRIPTION_ALREADY_EXISTS: "SUBSCRIPTION_ALREADY_EXISTS",

  // Subscription
  INVALID_SUBSCRIPTION_STATUS: "INVALID_SUBSCRIPTION_STATUS",
  SUBSCRIPTION_NOT_ACTIVE: "SUBSCRIPTION_NOT_ACTIVE",
  PLAN_NOT_AVAILABLE: "PLAN_NOT_AVAILABLE",

  // Promo Codes
  INVALID_PROMO_CODE: "INVALID_PROMO_CODE",
  PROMO_CODE_EXPIRED: "PROMO_CODE_EXPIRED",
  PROMO_CODE_NOT_ACTIVE: "PROMO_CODE_NOT_ACTIVE",
  PROMO_CODE_USAGE_LIMIT_REACHED: "PROMO_CODE_USAGE_LIMIT_REACHED",
  PROMO_CODE_NOT_APPLICABLE: "PROMO_CODE_NOT_APPLICABLE",

  // Payments
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",

  // External Services
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",

  // Server
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
