import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Bookmark, ExternalLink } from 'lucide-react';
import { useI18n } from '../../../app/providers/I18nProvider.jsx';
import { DashboardLayout } from '../../../app/layouts/DashboardLayout.jsx';
import Card from '../../../shared/components/ui/Card.jsx';
import Badge from '../../../shared/components/ui/Badge.jsx';
import Button from '../../../shared/components/ui/Button.jsx';
import EmptyState from '../../../shared/components/ui/EmptyState.jsx';
import { MarketTrendChart } from '../../market-intelligence/components/MarketTrendChart.jsx';
import { competitorProducts } from '../../market-intelligence/config/finalPreviewData.js';
import '../../market-intelligence/styles/MarketIntelligence.css';

export function ProductDetailPage() {
  const { t } = useI18n(); const navigate = useNavigate(); const { competitorId, productId } = useParams();
  const productList = competitorProducts[competitorId]; const product = productList?.find((item) => item.id === productId);
  const months = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'].map((month)=>t('marketScoped.months.'+month));
  if (!productList) return <DashboardLayout><div className="market-page"><EmptyState title={t('market.reference.notFoundCompetitor')} action={<Button onClick={()=>navigate('/market/competitors')}>{t('market.detail.back')}</Button>}/></div></DashboardLayout>;
  if (!product) return <DashboardLayout><div className="market-page"><EmptyState title={t('market.final.productNotFound')} action={<Button onClick={()=>navigate('/market/competitors/'+competitorId)}>{t('market.reference.backToCompetitor')}</Button>}/></div></DashboardLayout>;
  const related = productList.filter((item)=>item.id!==product.id).slice(0,4);
  const metrics = [['market.reference.demandSignal',t('marketScoped.common.high'),'+22%'],['market.reference.currentPrice',product.price+' JOD / '+t('marketProductData.perMonth'),'-5%'],['market.competitors.price','7.5 / 10','-0.4'],['market.reference.customerSentiment',t('marketScoped.common.positive'),'+6%']];
  const activity = [['marketScoped.product.priceUpdated','marketScoped.product.priceUpdatedDetail'],['marketScoped.product.promotion','marketScoped.common.previewActivity'],['marketScoped.product.searchIncreased','marketScoped.common.previewActivity'],['marketScoped.product.reviewsIncreased','marketScoped.common.previewActivity']];
  return <DashboardLayout><div className="market-page product-reference-page">
    <button type="button" className="reference-back" onClick={()=>navigate('/market/competitors/'+competitorId)}><ArrowLeft size={15}/>{t('market.reference.backToCompetitor')}</button>
    <header className="product-reference-header"><div className="product-reference-identity"><span className="product-provider-logo">orange</span><div><div><h1>{product.name}</h1><Badge variant="light-success">{t(product.statusKey)}</Badge></div><small>@{product.domain}　•　{t(product.categoryKey)}　•　{t(product.typeKey)}　•　{product.provider}</small><p>{t(product.descriptionKey)}</p></div></div><Button leadingIcon={<Bookmark size={15}/>}>{t('market.reference.trackProduct')}</Button></header>
    <section className="reference-kpi-grid">{metrics.map(([label,value,trend])=><Card className="reference-kpi" key={label}><small>{t(label)}</small><strong>{value}</strong><span>{trend}</span></Card>)}</section>
    <section className="reference-two-column reference-demand-row"><Card className="market-panel"><div className="market-panel__header"><div><h2>{t('market.reference.demandTrend')}</h2><p>{t('marketScoped.product.searchDemand')}</p></div><select className="market-filter-select"><option>{t('market.controls.last12')}</option></select></div><MarketTrendChart current={product.demand} previous={product.average} labels={months} ariaLabel={t('market.reference.demandTrend')} currentLabel={product.provider} previousLabel={t('marketProductData.industryAverage')}/></Card><Card className="market-panel reference-insights"><h2>{t('market.reference.keyInsights')}</h2><ul>{[1,2,3,4,5].map((index)=><li key={index}>{t('marketScoped.product.insight'+index)}</li>)}</ul></Card></section>
    <section className="reference-two-column"><Card className="market-panel"><h2>{t('market.detail.priceComparison')}</h2><p>{t('market.detail.priceComparisonSubtitle')}</p><div className="price-columns">{[['Orange',22],['Zain',24],['Umniah',26]].map(([name,value])=><div key={name}><strong>{value}</strong><i style={{height:(value*4)+'px'}}/><small>{name}</small></div>)}</div></Card><Card className="market-panel"><h2>{t('market.reference.packageDetails')}</h2><dl className="reference-details"><dt>{t('market.detail.productName')}</dt><dd>{product.name}</dd><dt>{t('market.final.category')}</dt><dd>{t(product.categoryKey)}</dd><dt>{t('market.final.type')}</dt><dd>{t(product.typeKey)}</dd><dt>{t('market.reference.currentPrice')}</dt><dd>{product.price} JOD / {t('marketProductData.perMonth')}</dd><dt>{t('market.reference.downloadSpeed')}</dt><dd>{product.download}</dd><dt>{t('market.reference.uploadSpeed')}</dt><dd>{product.upload}</dd><dt>{t('market.reference.contractPeriod')}</dt><dd>{t(product.contractKey)}</dd><dt>{t('market.reference.availability')}</dt><dd>{t(product.availabilityKey)}</dd><dt>{t('market.final.website')}</dt><dd><a href={product.website}>{product.website} <ExternalLink size={12}/></a></dd></dl></Card></section>
    <section className="reference-two-column"><Card className="market-panel sentiment-panel"><h2>{t('market.reference.customerSentiment')}</h2><div className="sentiment-donut"><strong>78%<small>{t('marketScoped.common.positive')}</small></strong></div><ul><li><span>{t('marketScoped.common.positive')}</span><b>78%</b></li><li><span>{t('marketScoped.common.neutral')}</span><b>15%</b></li><li><span>{t('marketScoped.common.negative')}</span><b>7%</b></li></ul></Card><Card className="market-panel"><div className="market-panel__header"><h2>{t('market.final.activity')}</h2><button className="market-link">{t('marketScoped.common.viewAll')}</button></div><div className="strategic-moves">{activity.map(([titleKey,copyKey],index)=><div key={titleKey}><span>●</span><strong>{t(titleKey)}<small>{t(copyKey)}</small></strong><small>{t('marketScoped.common.monthAgo',{count:index+1})}</small></div>)}</div></Card></section>
    <section className="market-panel related-products"><div className="market-panel__header"><div><h2>{t('market.reference.relatedProducts')}</h2><p>{t('marketScoped.product.otherProducts',{provider:product.provider})}</p></div><Button variant="secondary">{t('market.reference.allProducts')}</Button></div><div className="market-table-wrap"><table className="market-table"><thead><tr><th>{t('market.detail.productName')}</th><th>{t('market.final.category')}</th><th>{t('market.final.type')}</th><th>{t('market.reference.currentPrice')}</th><th>{t('marketScoped.common.actions')}</th></tr></thead><tbody>{related.map((item)=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{t(item.categoryKey)}</td><td>{t(item.typeKey)}</td><td>{item.price} / {t('marketProductData.perMonth')}</td><td><button className="market-table-action" onClick={()=>navigate('/market/competitors/'+competitorId+'/products/'+item.id)}>{t('marketScoped.common.viewDetails')}</button></td></tr>)}</tbody></table></div></section>
  </div></DashboardLayout>;
}
