import { cloneElement, isValidElement, useEffect, useId } from 'react';
import { Link, useBlocker } from 'react-router-dom';
import { AlertCircle, Search, ShieldCheck } from 'lucide-react';
import Button from '../../../shared/components/ui/Button.jsx';
import Modal from '../../../shared/components/ui/Modal.jsx';
import Skeleton from '../../../shared/components/ui/Skeleton.jsx';
import { useAdmin, useAdminText } from './AdminContext.jsx';

export { Button };
export function Heading({ title, description, actions, eyebrow }) { const { t } = useAdminText(); return <header className="pa-heading"><div><span className="pa-eyebrow">{t(eyebrow || 'platformScope')}</span><h1>{t(title)}</h1>{description && <p>{t(description)}</p>}</div>{actions && <div className="pa-actions">{actions}</div>}</header>; }
export function Panel({ title, children, actions, className = '' }) { return <section className={`pa-panel ${className}`}><header><h2>{title}</h2>{actions}</header>{children}</section>; }
export function Badge({ value }) { const { t } = useAdminText(); return <span className={`pa-badge pa-badge--${value}`}>{t(value)}</span>; }
export function DateValue({ value, time = false }) { const { locale, t } = useAdminText(); if (!value || Number.isNaN(Date.parse(value))) return t('unknown'); return <bdi>{new Intl.DateTimeFormat(locale, { dateStyle: 'medium', ...(time ? { timeStyle: 'short' } : {}) }).format(new Date(value))}</bdi>; }
export function Identity({ name, email, to }) { const content = <><span className="pa-avatar" aria-hidden="true">{(name || email || '?').split(/\s/).slice(0, 2).map(s => s[0]).join('')}</span><span><strong>{name || email}</strong>{email && name && <small dir="ltr">{email}</small>}</span></>; return to ? <Link className="pa-identity" to={to}>{content}</Link> : <div className="pa-identity">{content}</div>; }
export function Field({ label, children, ...props }) { const id = useId(); return <label className="pa-field" htmlFor={id}><span>{label}</span>{isValidElement(children) ? cloneElement(children, { id }) : <input id={id} {...props} />}</label>; }
export function SelectField({ label, value, onChange, options, disabled }) { const id = useId(); return <label className="pa-field" htmlFor={id}><span>{label}</span><select id={id} value={value ?? ''} onChange={e => onChange(e.target.value)} disabled={disabled}>{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }
export function Empty({ message = 'empty' }) { const { t } = useAdminText(); return <div className="pa-empty"><Search size={28} aria-hidden="true" /><p>{t(message)}</p></div>; }
export function QueryState({ query, children }) { const { t } = useAdminText(); if (query.isPending) return <div role="status" aria-label={t('loading')} className="pa-loading"><Skeleton height="90px" /><Skeleton height="280px" /></div>; if (query.isError) return <div className="pa-empty" role="alert"><AlertCircle size={30} /><h2>{t(query.error?.code === 'notFound' ? 'notFound' : 'error')}</h2><Button onClick={() => query.refetch()}>{t('retry')}</Button></div>; return children; }
export function Forbidden({ notFound = false }) { const { t } = useAdminText(); return <div className="pa-empty"><ShieldCheck size={42} /><span className="pa-eyebrow">{notFound ? '404' : '403'}</span><h1>{t(notFound ? 'unknownRoute' : 'forbiddenTitle')}</h1><p>{t(notFound ? 'notFound' : 'forbidden')}</p><Link className="pa-link-button" to="/admin">{t('back')}</Link></div>; }
export function Permission({ permission, children }) { const admin = useAdmin(); return admin.can(permission) ? children : <Forbidden />; }
export function Confirmation({ open, title, children, onClose, onConfirm, busy = false, disabled = false, confirmLabel = 'confirm', cancelLabel = 'cancel' }) { const { t } = useAdminText(); return <Modal className="pa-dialog" isOpen={open} onClose={busy ? () => {} : onClose} title={title || t('review')} closeLabel={t('close')} maxWidth="640px" footer={<><Button variant="outline" disabled={busy} onClick={onClose}>{t(cancelLabel)}</Button><Button onClick={onConfirm} disabled={disabled} loading={busy} loadingLabel={t('saving')}>{t(confirmLabel)}</Button></>}>{children}</Modal>; }
export function UnsavedGuard({ dirty }) {
  const { t } = useAdminText(); const blocker = useBlocker(dirty);
  useEffect(() => { if (!dirty) return; const handler = e => { e.preventDefault(); e.returnValue = ''; }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  return <Confirmation open={blocker.state === 'blocked'} title={t('unsaved')} cancelLabel="stay" confirmLabel="discard" onClose={() => blocker.reset?.()} onConfirm={() => blocker.proceed?.()}><p>{t('unsavedBody')}</p></Confirmation>;
}
export function Tabs({ items, value, onChange }) { const { t, dir } = useAdminText(); const prefix = useId(); return <div className="pa-tabs" role="tablist" onKeyDown={event => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const index = items.indexOf(value); const next = event.key === 'Home' ? 0 : event.key === 'End' ? items.length - 1 : (index + (event.key === (dir === 'rtl' ? 'ArrowLeft' : 'ArrowRight') ? 1 : -1) + items.length) % items.length; onChange(items[next]); document.getElementById(`${prefix}-${items[next]}`)?.focus(); }}>{items.map(item => <button type="button" id={`${prefix}-${item}`} key={item} role="tab" aria-selected={value === item} tabIndex={value === item ? 0 : -1} onClick={() => onChange(item)}>{t(item)}</button>)}</div>; }
export function DefinitionList({ items }) { return <dl className="pa-definitions">{items.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value ?? '—'}</dd></div>)}</dl>; }
