import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { BarChart3, Download, Lightbulb, Search, Sparkles, TrendingUp, Wifi } from 'lucide-react';
import { useI18n } from '../../../app/providers/I18nProvider.jsx';
import { DashboardLayout } from '../../../app/layouts/DashboardLayout.jsx';
import PageHeader from '../../../shared/components/layout/PageHeader.jsx';
import Card from '../../../shared/components/ui/Card.jsx';
import Button from '../../../shared/components/ui/Button.jsx';
import Badge from '../../../shared/components/ui/Badge.jsx';
import EmptyState from '../../../shared/components/ui/EmptyState.jsx';
import Modal from '../../../shared/components/ui/Modal.jsx';
import { MarketTabs } from '../components/MarketTabs.jsx';
import { MarketTrendChart, SeasonalBarChart } from '../components/MarketTrendChart.jsx';
import { opportunities, opportunitySummary } from '../config/finalPreviewData.js';
import '../styles/MarketIntelligence.css';

const OpportunityCard = ({item,onDetails,t}) => <Card className="reference-opportunity-card"><div className="opportunity-card-heading"><span><Wifi size={20}/></span><strong>{t(item.shortTitleKey)}</strong><Badge variant={item.potentialKey.endsWith('high')?'light-success':'warning'}>{t(item.potentialKey)}</Badge></div><p>{t(item.descriptionKey)}</p><dl><div><dt>{t('marketScoped.opportunities.marketSizeShort')}</dt><dd>{item.marketSize}</dd></div><div><dt>{t('marketScoped.opportunities.demandGrowth')}</dt><dd>{item.growth}</dd></div><div><dt>{t('marketScoped.opportunities.competition')}</dt><dd>{t(item.competitionKey)}</dd></div></dl><button type="button" onClick={()=>onDetails(item.id)}>{t('marketScoped.common.viewDetails')} →</button></Card>;
export function MarketOpportunitiesPage() {
  const {t}=useI18n(); const navigate=useNavigate(); const [query,setQuery]=useState(''); const [category,setCategory]=useState('all'); const [potential,setPotential]=useState('all');
  const filtered=useMemo(()=>opportunities.filter((item)=>(category==='all'||item.categoryKey===category)&&(potential==='all'||item.potentialKey===potential)&&t(item.titleKey).toLowerCase().includes(query.toLowerCase())),[category,potential,query,t]);
  const details=(id)=>navigate('/market/opportunities/'+id);
  const categories=['marketScoped.category.homeInternet','marketScoped.category.smartHome','marketScoped.category.mobile','marketScoped.category.business','marketScoped.category.digitalServices'];
  const potentials=['marketScoped.common.high','marketScoped.common.medium','marketScoped.common.low'];
  return <DashboardLayout><div className="market-page opportunities-reference-page">
    <PageHeader title={t('market.final.opportunitiesTitle')} subtitle={t('market.reference.opportunitiesSubtitle')} actions={<Button variant="secondary" leadingIcon={<Download size={15}/>}>{t('market.reference.exportReport')}</Button>}/><MarketTabs/>
    <section className="reference-kpi-grid">{opportunitySummary.map((item)=><Card className="reference-kpi" key={item.id}><small>{t(item.labelKey)}</small><strong>{item.value}</strong><span>+{item.trend} {t('marketScoped.common.lastPeriod')}</span></Card>)}</section>
    <Card className="opportunity-ai-insight"><span><Sparkles size={19}/></span><div><h2>{t('marketScoped.opportunities.aiTitle')}</h2><p>{t('marketScoped.opportunities.aiText')}</p></div><Button variant="secondary">{t('marketScoped.opportunities.fullAnalysis')} →</Button></Card>
    <div className="opportunity-filter-row"><select value={category} onChange={(event)=>setCategory(event.target.value)} aria-label={t('marketScoped.opportunities.industry')}><option value="all">{t('marketScoped.common.all')}</option>{categories.map((key)=><option key={key} value={key}>{t(key)}</option>)}</select><select aria-label={t('marketScoped.opportunities.opportunityType')}><option>{t('marketScoped.opportunities.opportunityType')}: {t('marketScoped.common.all')}</option></select><select value={potential} onChange={(event)=>setPotential(event.target.value)} aria-label={t('marketScoped.opportunities.potential')}><option value="all">{t('marketScoped.common.all')}</option>{potentials.map((key)=><option key={key} value={key}>{t(key)}</option>)}</select><select aria-label={t('marketScoped.opportunities.timePeriod')}><option>{t('marketScoped.opportunities.next12')}</option></select><label><Search size={15}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={t('marketScoped.opportunities.search')} aria-label={t('marketScoped.opportunities.search')}/></label></div>
    <section className="market-panel"><div className="market-panel__header"><div><h2>{t('market.reference.topOpportunities')}</h2><p>{t('marketScoped.opportunities.topSubtitle')}</p></div><button className="market-link">{t('marketScoped.common.viewAll')}</button></div><div className="reference-top-opportunities">{filtered.slice(0,3).map((item)=><OpportunityCard key={item.id} item={item} onDetails={details} t={t}/>)}</div></section>
    <section className="market-panel opportunity-table-panel"><div className="market-panel__header"><div><h2>{t('market.reference.allOpportunities')}</h2><p>{t('marketScoped.opportunities.allSubtitle')}</p></div><select aria-label={t('marketScoped.opportunities.sortPotential')}><option>{t('marketScoped.opportunities.sortPotential')}</option></select></div>{filtered.length?<div className="market-table-wrap"><table className="market-table"><thead><tr><th>{t('marketScoped.opportunities.opportunity')}</th><th>{t('marketScoped.opportunities.category')}</th><th>{t('marketScoped.opportunities.marketSize')}</th><th>{t('marketScoped.opportunities.demandGrowth')}</th><th>{t('marketScoped.opportunities.competition')}</th><th>{t('marketScoped.opportunities.potential')}</th><th>{t('marketScoped.common.actions')}</th></tr></thead><tbody>{filtered.map((item)=><tr key={item.id}><td><strong>{t(item.shortTitleKey)}</strong><small>{t(item.typeKey)}</small></td><td>{t(item.categoryKey)}</td><td>{item.marketSize}</td><td className="positive-number">{item.growth}</td><td><Badge variant={item.competitionKey.endsWith('low')?'light-success':'warning'}>{t(item.competitionKey)}</Badge></td><td><Badge variant={item.potentialKey.endsWith('high')?'light-success':'warning'}>{t(item.potentialKey)}</Badge></td><td><button className="market-table-action" onClick={()=>details(item.id)}>{t('marketScoped.common.viewDetails')}</button></td></tr>)}</tbody></table><div className="reference-pagination">{t('marketScoped.opportunities.showing')}</div></div>:<EmptyState title={t('market.final.empty')}/>}</section>
    <section className="market-panel market-trends-strip"><div className="market-panel__header"><h2>{t('market.reference.marketTrends')}</h2></div><div>{[['marketScoped.opportunities.remoteWork','marketScoped.opportunities.remoteWorkText','+35%',TrendingUp],['marketScoped.opportunities.digitalAdoption','marketScoped.opportunities.digitalAdoptionText','+28%',BarChart3],['marketScoped.opportunities.smartInterest','marketScoped.opportunities.smartInterestText','+42%',Lightbulb]].map(([titleKey,textKey,value,Icon])=><Card key={titleKey}><Icon size={17}/><strong>{t(titleKey)}</strong><b>{value}</b><p>{t(textKey)}</p></Card>)}</div></section>
  </div></DashboardLayout>;
}
export function OpportunityDetailPage() {
  const {t}=useI18n(); const navigate=useNavigate(); const {opportunityId}=useParams(); const item=opportunities.find((entry)=>entry.id===opportunityId); const [tracked,setTracked]=useState(false); const months=['jan','feb','mar','apr','may','jun'].map((month)=>t('marketScoped.months.'+month));
  return <><MarketOpportunitiesPage/><Modal isOpen onClose={()=>navigate('/market/opportunities')} title={t('market.reference.opportunityDetails')} maxWidth="920px" className="opportunity-details-modal">{!item?<EmptyState title={t('market.final.opportunityNotFound')}/>:<div className="opportunity-modal-content"><p className="modal-subtitle">{t('market.reference.opportunityDetailsSubtitle')}</p><Card className="opportunity-modal-hero"><span><Wifi size={29}/></span><div><h3>{t(item.titleKey)} <Badge variant="light-success">{t(item.potentialKey)}</Badge></h3><p>{t(item.descriptionKey)}</p></div><Button onClick={()=>setTracked((value)=>!value)}>{tracked?t('marketScoped.opportunities.tracked'):t('marketScoped.opportunities.track')}</Button></Card><section className="reference-kpi-grid">{[['marketScoped.opportunities.demandSignal',t('marketScoped.common.high'),'+22%'],['marketScoped.opportunities.demandGrowth',item.growth,'+18%'],['marketScoped.opportunities.competitionLevel',t(item.competitionKey),'-2'],['marketScoped.opportunities.customerSentiment',t('marketScoped.common.positive'),'+12%']].map(([label,value,trend])=><Card className="reference-kpi" key={label}><small>{t(label)}</small><strong>{value}</strong><span>{trend}</span></Card>)}</section><section className="reference-two-column opportunity-charts"><Card className="market-panel"><h3>{t('market.reference.demandTrend')}</h3><MarketTrendChart current={item.trend} previous={item.trend.map((value)=>value*.7)} labels={months} ariaLabel={t('market.reference.demandTrend')} currentLabel={t('market.reference.demandTrend')} previousLabel={t('marketProductData.industryAverage')}/></Card><Card className="market-panel"><h3>{t('marketScoped.opportunities.competitorActivity')}</h3><SeasonalBarChart historical={item.competitorActivity.map(()=>0)} current={item.competitorActivity} labels={months} ariaLabel={t('marketScoped.opportunities.competitorActivity')}/></Card></section><Card className="market-panel numbered-list"><h3>{t('market.reference.keyInsights')}</h3><ul>{item.insightKeys.map((key)=><li key={key}>{t(key)}</li>)}</ul></Card><Card className="market-panel numbered-list recommendations"><h3>{t('market.reference.recommendedActions')}</h3><ol>{item.actionKeys.map((key)=><li key={key}>{t(key)}</li>)}</ol></Card></div>}</Modal></>;
}
